doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        use_savepoints: true
        mapping_types:
            enum: string
        server_version: '10.11'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci